{% set name = "contourpy" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/contourpy-{{ version }}.tar.gz
  sha256: 1a5882aaf48c4ed0100853aa158ea03f275b8f1374a995747406b316ef811016

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - pybind11 >=2.6
    - python
  run:
    - numpy >=1.16
    - python

test:
  imports:
    - contourpy
    - contourpy.util
  commands:
    - pip check
    - python -c "import contourpy as c; c.contour_generator(None, None, [[0, 1], [2, 3]]).lines(0.9)"
  requires:
    - pip

about:
  home: https://github.com/contourpy/contourpy
  summary: Calculating contours of 2D quadrilateral grids from Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ianthomas23
